### ISSUE TITLE
No signature of Method error

### ISSUE THREAD

**Issue by aquarianharsha** [DaveGut/Cloud-Based_TP-Link-to-SmartThings-Integration#3]
I'm trying to follow the instruction on Read Me, When I copy any one of the *.groovy code and paste it into the code section in new smart app page
I get the below error-
```
No signature of method: script_app_metadata_8ea58855_7a03_4abf_bb1a_67b763b70c08.metadata() is applicable for argument types: (script_app_metadata_8ea58855_7a03_4abf_bb1a_67b763b70c08$_run_closure1) values: [script_app_metadata_8ea58855_7a03_4abf_bb1a_67b763b70c08$_run_closure1@1298ea45] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)
```

**Comment by aquarianharsha** [comment]
This for -Cloud-Based TP-Link to Smart Things Integration

**Comment by marti314** [comment]
Also getting this same error when I try to create the smart app: 
No signature of method: script_app_metadata_1302cd86_2fc9_443a_880d_5f2226c809b2.metadata() is applicable for argument types: (script_app_metadata_1302cd86_2fc9_443a_880d_5f2226c809b2$_run_closure1) values: [script_app_metadata_1302cd86_2fc9_443a_880d_5f2226c809b2$_run_closure1@568ca260] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by DaveGut** [comment]
sorry for the delay.  Information provided is very limited.  Possible problems:  


device handler pasted into a Smart App blank page or vice-a-versa
missing character in the code caused by copy/paste error.
