### ISSUE TITLE
Your current token: null

### ISSUE THREAD

**Issue by ShaunTheBaa** [DaveGut/Cloud-Based_TP-Link-to-SmartThings-Integration#4]
Do you require a smart things hub for this to work?
It says go to my devices but the only device in there I see my oled smart tv.
Also when trying to add the devices in the app it says Your current token: null.
If you do require a smart things hub, that would be the problem, as they are illegal in Australia due to the restricted frequency they use.
![image](https://user-images.githubusercontent.com/33796730/34504915-4eced6ce-f06d-11e7-8aee-c8b0df216f98.jpg)

**Comment by DaveGut** [comment]
you need a smart things hub.  If not, there will not be communications.
