### ISSUE TITLE
Support for HS220 dimmer switch

### ISSUE THREAD

**Issue by torkcm** [DaveGut/Cloud-Based_TP-Link-to-SmartThings-Integration#8]
I just got this switch and dimmer functionality isn't supported. I was able to modify the code added this to make it work.
def setLevel(percentage) {
	percentage = percentage as int
	sendCmdtoServer("""{"smartlife.iot.dimmer":{"set_brightness":{"brightness":${percentage}}}}""", "deviceCommand", "commandResponse")
}

I noticed though percentage can't be 0, only 1-100.

**Comment by DaveGut** [comment]
I will set up a test file.  In addition to the command, I need to know the response.

Does the on/off functionality work??

**Comment by torkcm** [comment]
Yes on/off works as is. Let me get a response for you.

**Comment by torkcm** [comment]
5:35:43 PM: debug [smartlife.iot.dimmer:[set_brightness:[err_code:0]]] 

5:34:54 PM: info HS220 Bar Light: Power: on

5:34:54 PM: debug [system:[get_sysinfo:[next_action:[type:-1], mic_type:IOT.SMARTPLUGSWITCH, model:HS220(US), dev_name:Smart Wi-Fi Dimmer, alias:Bar Light, mac:AC:84:C6:56:EC:DB, fwId:00000000000000000000000000000000, updating:0, on_time:1, brightness:60, err_code:0, icon_hash:, longitude_i:-769127, hw_ver:1.0, latitude_i:388316, feature:TIM, hwId:84DCCF37225C9E55319617F7D5C095BD, rssi:-55, active_mode:none, preferred_state:[[brightness:100, index:0], [brightness:75, index:1], [brightness:50, index:2], [brightness:25, index:3]], sw_ver:1.4.8 Build 180109 Rel.171240, oemId:3B13224B2807E0D48A9DD06EBD344CD6, deviceId:80060B625B42EECBA99A07C6B5CEE9D21A04F99D, led_off:0, relay_state:1]]]

5:34:54 PM: debug [system:[set_relay_state:[err_code:0]]]

5:34:38 PM: debug [system:[set_relay_state:[err_code:0]]]

5:34:39 PM: info HS220 Bar Light: Power: off

5:34:39 PM: debug [system:[get_sysinfo:[next_action:[type:-1], mic_type:IOT.SMARTPLUGSWITCH, model:HS220(US), dev_name:Smart Wi-Fi Dimmer, alias:Bar Light, mac:AC:84:C6:56:EC:DB, fwId:00000000000000000000000000000000, updating:0, on_time:0, brightness:60, err_code:0, icon_hash:, longitude_i:-769127, hw_ver:1.0, latitude_i:388316, feature:TIM, hwId:84DCCF37225C9E55319617F7D5C095BD, rssi:-54, active_mode:none, preferred_state:[[brightness:100, index:0], [brightness:75, index:1], [brightness:50, index:2], [brightness:25, index:3]], sw_ver:1.4.8 Build 180109 Rel.171240, oemId:3B13224B2807E0D48A9DD06EBD344CD6, deviceId:80060B625B42EECBA99A07C6B5CEE9D21A04F99D, led_off:0, relay_state:0]]]

**Comment by DaveGut** [comment]
Today, I added a device handler and modified the service manager to accommodate the HS220.  Thank you for the information.  If there are issues, add a new issue.
